export const GET_GENRES_W_ARTISTS_SUCCESS = 'GET_GENRES_W_ARTISTS_SUCCESS';
export const GET_GENRES_W_ARTISTS_FAILULRE = 'GET_GENRES_W_ARTISTS_FAILULRE';
export const POST_FEEDBACK_SUCCESS = 'POST_FEEDBACK_SUCCESS';
export const POST_FEEDBACK_FAILURE = 'POST_FEEDBACK_FAILURE';
